function value = mf_eqn_line(sval, mval, r, l, c, m_BC, k)

value = l * (([0; mval(1:(1 / k) - 3)] ...
    + [mval(2:(1 / k) - 2); m_BC] ...
    - 2.0 * mval) / (k^2) ... % Second deriv
    + 2.0 * r.^(-1) .* ([mval(2:(1 / k) - 2); m_BC] ... 
    - [0; mval(1:(1 / k) - 3)]) / (2.0 * k) ... % 1st deriv
    - (2.0 * mval) .* r.^(-2)) ...
    - mval.^3 + mval + (4.0 / 3.0) * c * sval .* mval;

end