function answer = s_eqn_ferro(sval, mval, r, t, l, c, s_BC, k)

% Change this to sixth-order
eqn = l * (([zeros(1, 1 / k); sval(1:(1 / k) - 3, :)] ...
    + [sval(2:(1 / k) - 2, :); s_BC * ones(1, 1 / k)] ...
    - 2.0 * sval) / (k^2) ... % Second deriv
    + 2.0 * r.^(-1) .* ([sval(2:(1 / k) - 2, :); s_BC * ones(1, 1 / k)] ... 
    - [zeros(1, 1 / k); sval(1:(1 / k) - 3, :)]) / (2.0 * k) ... % 1st deriv
    - (6.0 * sval) .* r.^(-2)) ...
    - t * sval + sqrt(6.0) * sval.^2 - (4.0 / 3.0) * sval.^3 ...
    - c * mval.^3;

answer=eqn;
end