function value = sf_eqn_line(sval, mval, r, t, l, c, s_BC, k)

value = l * (([0; sval(1:(1 / k) - 3)] ...
    + [sval(2:(1 / k) - 2); s_BC] ...
    - 2.0 * sval) / (k^2) ... % Second deriv
    + 2.0 * r.^(-1) .* ([sval(2:(1 / k) - 2); s_BC] ... 
    - [0; sval(1:(1 / k) - 3)]) / (2.0 * k) ... % 1st deriv
    - (6.0 * sval) .* r.^(-2)) ...
    - t * sval + sqrt(6.0) * sval.^2 - (4.0 / 3.0) * sval.^3 ...
    + c * mval.^2;

end